resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/10.yaml
packages:
- xmobar
- xmonad
- xmonad-contrib
extra-deps:
- netlink-1.1.1.0
flags:
  xmobar:
    all_extensions: true
