#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Set up an icon tray

trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --transparent true --alpha 0 --tint 0x282c34 --height 25 &

# trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --monitor 1 --transparent true --alpha 180 --tint 0x282c34  --height 22 &

# Set the default X cursor to the usual pointer
xsetroot -cursor_name left_ptr

# Set a nice background
feh --randomize --bg-fill ~/.local/share/wallpapers/*

# Volume Manager
if [ -x /usr/bin/nm-applet ] ; then
    pasystray &
fi

# Power Manager
if [ -x /usr/bin/nm-applet ] ; then
    xfce4-power-manager &
fi

# Network Manager
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

firefox &
emacs --eval "(server-start)" &

ssh-agent dbus-run-session -- xmonad
