#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Set up an icon tray

trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --transparent true --alpha 0 --tint 0x282c34 --height 25 &

# trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --monitor 1 --transparent true --alpha 180 --tint 0x282c34  --height 22 &

# Set the default X cursor to the usual pointer
xsetroot -cursor_name left_ptr

# Set a nice background
feh --randomize --bg-fill ~/.local/share/wallpapers/*

# Volume Manager
if [ -x /usr/bin/pasystray ] ; then
    pasystray &
fi

# Power Manager
if [ -x /usr/bin/xfce4-power-manager ] ; then
    xfce4-power-manager &
fi

# Network Manager
if [ -x /bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

# Notification Daemon, need to be started after x11 display
# if [ -x /bin/dunst ] ; then
#    dunst &
# fi

# Protect eyes from strain
if [ -x /bin/redshift ] ; then
   # redshift -l 12.98:77.58 -t 4500:2500 -b 1.0:0.8 &
   redshift -O 4000
fi

# flatpak run com.microsoft.Teams
google-chrome-stable &
# emacs --eval "(server-start)" &

# start the emacs daemon to replace vi/vim usage
emacs --bg-daemon=term

# ssh-agent dbus-run-session -- xmonad
exec dbus-launch --sh-syntax --exit-with-session xmonad
