#!/bin/sh

# source ~/.config/shell/profile

xrandr --dpi 142
~/.local/bin/custom/remaps
redshift -l 12.98:77.58 -t 4500:2500 -b 1.0:0.8 &

# autostart="xcompmgr pipewire pipewire-pulse"
# # autostart="mpd xcompmgr dunst unclutter pipewire"

# for program in $autostart; do
# 	pidof -s "$program" || "$program" &
# done >/dev/null 2>&1
