# -*- mode: yaml-ts; -*-

# Xmonad, Xmobar
# Reference: https://brianbuccola.com/how-to-install-xmonad-and-xmobar-via-stack/

resolver: lts-20.18
# resolver: ghc-9.2.7

packages:
- xmobar
- xmonad
- xmonad-contrib

# extra-deps: []
extra-deps:
- netlink-1.1.1.0

# flags: {}
flags:
  xmobar:
    all_extensions: true

extra-package-dbs: []

# system-ghc: true
compiler-check: newer-minor
